In [1]:
import numpy as np
import torch 
import h5py as h

In [2]:
loss = torch.nn.MSELoss()
features_list = np.load(f'/home/falhamdoosh/disentagledFeaturesExtractor/eval_out/feat_test.npy')

input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(torch.tensor(features_list[50]), torch.tensor(features_list[100]))
print(features_list[0][100:110])
print(output)

[ 0.02175061  0.00085695 -0.00951961 -0.00182464  0.0290191   0.00295314
  0.00591691 -0.0439623  -0.058594   -0.00741401]
tensor(0.0002)


In [87]:

img_test=r"/home/falhamdoosh/disentagledFeaturesExtractor/multi_manip/test/triplets_N_8.h5"
img_arr=h.File(img_test)


In [42]:
len(img_arr['manip'][0])

151

In [88]:
v=img_arr['manip'][0]

In [89]:
attr=np.loadtxt(r"/home/falhamdoosh/disentagledFeaturesExtractor/splits/Shopping100k/attr_num.txt",dtype=int)

In [45]:
attr


array([16, 17, 19, 14, 10, 15,  2, 11, 16,  7,  9, 15])

In [63]:

cut_index=[]
print (cut_index)
start=0
for i ,num_attr in enumerate(attr):
    print (i)
    cut_index.append((start,start+num_attr))
    start+=num_attr
    print(cut_index[i])
  

[]
0
(0, 16)
1
(16, 33)
2
(33, 52)
3
(52, 66)
4
(66, 76)
5
(76, 91)
6
(91, 93)
7
(93, 104)
8
(104, 120)
9
(120, 127)
10
(127, 136)
11
(136, 151)


In [64]:
split_index=[inx[1] for i,inx in enumerate (cut_index)]  

In [65]:
split_index

[16, 33, 52, 66, 76, 91, 93, 104, 120, 127, 136, 151]

In [66]:
Nsplit=np.split(v,split_index[:-1])

In [67]:
Nsplit

[array([ 0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
         0,  0]),
 array([ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0, -1,  0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 0,  0,  0,  0,  1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0]),
 array([ 1, -1]),
 array([ 0,  0,  0,  0,  1,  0,  0,  0, -1,  0,  0]),
 array([ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0, -1,  0,  0,  0]),
 array([0, 0, 0, 0, 0, 0, 0]),
 array([ 1,  0,  0,  0,  0,  0, -1,  0,  0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]

In [68]:
len(Nsplit)

12

In [77]:
manip_array=np.zeros((12,151),dtype=int)

for j in range(manip_array.shape[0]): 
    start,end=cut_index[j][0],cut_index[j][1]
    manip_array[j][start:end]=Nsplit[j]
    print(manip_array[j])

[ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  1  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0

In [79]:
print(manip_array[2])

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  1  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0]


In [82]:
manip_array=manip_array[~np.all(manip_array == 0, axis=1)]

In [83]:
manip_array.shape

(8, 151)

In [90]:
#helping list keep in init func
cut_index=[]
start=0
for i ,num_attr in enumerate(attr):
    cut_index.append((start,start+num_attr))
    start+=num_attr
split_index=[inx[1] for i,inx in enumerate (cut_index)] 
####

def get_manip_array(v):
    Nsplit=np.split(v,split_index[:-1])
    manip_array=np.zeros((12,151),dtype=int)
    for j in range(manip_array.shape[0]):
        start,end=cut_index[j][0],cut_index[j][1]
        manip_array[j][start:end]=Nsplit[j]
    return manip_array[~np.all(manip_array == 0, axis=1)]
    

In [92]:
import time
start= time.time()
get_manip_array(v)
print("--- %s seconds ---" % (time.time() - start))

--- 0.00021314620971679688 seconds ---


In [94]:
attr_num=attr
def split_manip(multi_manip): # [0, 1, 0, -1 | 0, 0, 0 ,0 | 0, 1, 0 ]
    manip_list = []
    offset = 0
    for i, attr_len in enumerate(attr_num): 
        manip = np.zeros(len(multi_manip), dtype='int')
        found_non_zero = False
        for j in range(attr_len):
            if multi_manip[j + offset] != 0:
                manip[j + offset] = multi_manip[j + offset]
                found_non_zero = True
        if found_non_zero == True:
            manip_list.append(manip)
        offset += attr_len

    return manip_list


In [95]:
import time
start= time.time()
split_manip(v)
print("--- %s seconds ---" % (time.time() - start))

--- 0.00028634071350097656 seconds ---
